# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, 3.10, 3.11 ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/setup.py') }}-${{ hashFiles('.github/dependabot/constraints.txt') }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip

        if [ ! ${{ matrix.python-version }} == "3.6" ]; then
          #  Our constraints can't be applied to python 3.6
          python3 -m pip install ".[test]" --constraint .github/dependabot/constraints.txt
        else
          python3 -m pip install ".[test]"
        fi

    - name: Test with pytest
      run: |
        python3 -m pytest -s --verbose --cov=vip_ipykernel

    - uses: codecov/codecov-action@v1
